server {
    listen 80;
    server_tokens off;
    root /usr/share/nginx/html;
    index index.html;

    # JSON files: no-cache + CORS
    location ~* \.(json)$ {
        add_header Cache-Control "no-cache, must-revalidate";
        add_header Access-Control-Allow-Origin "*";
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
